parameters:
    trovit.cron_manager.model.command_execute.class_path: Trovit\CronManagerBundle\Model\CommandExecute
    trovit.cron_manager.model.command_validator.class_path: Trovit\CronManagerBundle\Model\CommandValidator
    trovit.cron_manager.model.cron_dispatcher.class_path: Trovit\CronManagerBundle\Model\CronDispatcher
    trovit.cron_manager.model.create_cron_task.class_path: Trovit\CronManagerBundle\Model\CRUD\CreateCronTask
    trovit.cron_manager.model.delete_cron_task.class_path: Trovit\CronManagerBundle\Model\CRUD\DeleteCronTask
    trovit.cron_manager.model.read_cron_task.class_path: Trovit\CronManagerBundle\Model\CRUD\ReadCronTask
    trovit.cron_manager.model.update_cron_task.class_path: Trovit\CronManagerBundle\Model\CRUD\UpdateCronTask
    trovit.cron_manager.model.date_time_wrapper.class_path: Trovit\CronManagerBundle\Model\DateTimeWrapper
    trovit.cron_manager.model.cron_expression_wrapper.class_path: Trovit\CronManagerBundle\Model\CronExpressionWrapper
    trovit.cron_manager.validator.constraints.command_exists.class_path: Trovit\CronManagerBundle\Validator\Constraints\CommandExistsValidator
    trovit.cron_manager.validator.constraints.valid_cron_expression.class_path: Trovit\CronManagerBundle\Validator\Constraints\ValidCronExpressionValidator
